# -*- coding: utf-8 -*-
"""Predictive Maintenance Model for Aircraft Engines

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PYEobjoZWKBj8ixPwADB40-Jf3BdsaAE
"""

import os, sys, random, warnings
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import tensorflow as tf
from tensorflow.keras import mixed_precision
from tensorflow.keras import callbacks, layers, models, optimizers

from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.model_selection import GroupShuffleSplit
from sklearn.preprocessing import StandardScaler

warnings.filterwarnings("ignore")
sns.set_theme(style="whitegrid")

SEED = 42
os.environ["PYTHONHASHSEED"] = str(SEED)
random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)

WINDOW_SIZE = 50
STRIDE = 1
RUL_CAP = 125
BATCH_SIZE = 256
EPOCHS = 40
LEARNING_RATE = 1e-3
VALIDATION_SPLIT = 0.15

gpus = tf.config.list_physical_devices("GPU")
print("GPUs detected:", gpus)

if gpus:
    try:
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
        print("Memory growth enabled.")
    except RuntimeError as e:
        print("Memory growth could not be changed:", e)
        print("Continuing with Colab's existing GPU configuration.")

    mixed_precision.set_global_policy("mixed_float16")

    try:
        tf.config.optimizer.set_jit(True)
        print("XLA JIT enabled.")
    except Exception as e:
        print("XLA JIT could not be enabled:", e)

    print("Using GPU acceleration.")
else:
    print("No GPU detected. In Colab, switch Runtime -> GPU.")

IN_COLAB = "google.colab" in sys.modules
DATA_DIR = Path("/content") if IN_COLAB else Path.cwd()

TRAIN_PATH = DATA_DIR / "train_FD001.txt"
TEST_PATH = DATA_DIR / "test_FD001.txt"
RUL_PATH = DATA_DIR / "RUL_FD001.txt"

missing = [p.name for p in [TRAIN_PATH, TEST_PATH, RUL_PATH] if not p.exists()]
if missing and IN_COLAB:
    from google.colab import files
    print("Upload:", missing)
    files.upload()

def load_cmapss(path):
    df = pd.read_csv(path, sep=r"\s+", header=None, engine="python")
    df = df.dropna(axis=1, how="all")
    return df

train_raw = load_cmapss(TRAIN_PATH)
test_raw = load_cmapss(TEST_PATH)
rul_truth = pd.read_csv(RUL_PATH, header=None).iloc[:, 0].to_numpy(dtype=np.float32)

n_cols = train_raw.shape[1]
col_names = (
    ["engine", "cycle"]
    + [f"op_setting_{i}" for i in range(1, 4)]
    + [f"sensor_{i}" for i in range(1, (n_cols - 5) + 1)]
)

train_raw.columns = col_names
test_raw.columns = col_names

print(train_raw.shape, test_raw.shape, rul_truth.shape)
train_raw.head()

def compute_train_rul(df, cap):
    out = df.copy()
    max_cycles = out.groupby("engine")["cycle"].transform("max")
    out["RUL"] = (max_cycles - out["cycle"]).clip(lower=0, upper=cap)
    out["RUL_norm"] = out["RUL"] / cap
    return out

sensor_cols = [c for c in train_raw.columns if c.startswith("sensor_")]
op_cols = [c for c in train_raw.columns if c.startswith("op_setting_")]
feature_cols = op_cols + sensor_cols

train = compute_train_rul(train_raw, RUL_CAP)

scaler = StandardScaler()
scaler.fit(train[feature_cols])

def scale_frame(df):
    scaled = pd.DataFrame(
        scaler.transform(df[feature_cols]),
        columns=feature_cols,
        index=df.index,
    )
    for col in ["engine", "cycle", "RUL", "RUL_norm"]:
        if col in df.columns:
            scaled[col] = df[col].values
    return scaled

train_scaled = scale_frame(train)
test_scaled = scale_frame(test_raw)

def create_train_sequences(df, window, stride):
    X, y, groups = [], [], []
    for engine_id, df_e in df.groupby("engine"):
        df_e = df_e.sort_values("cycle")
        values = df_e[feature_cols].to_numpy(dtype=np.float32)
        targets = df_e["RUL_norm"].to_numpy(dtype=np.float32)

        if len(values) < window:
            continue

        for start in range(0, len(values) - window + 1, stride):
            end = start + window
            X.append(values[start:end])
            y.append(targets[end - 1])
            groups.append(engine_id)

    return np.asarray(X, dtype=np.float32), np.asarray(y, dtype=np.float32), np.asarray(groups)

def create_test_windows(df, rul_values, window, cap):
    X, y = [], []
    engine_ids = sorted(df["engine"].unique())

    for idx, engine_id in enumerate(engine_ids):
        df_e = df[df["engine"] == engine_id].sort_values("cycle")
        values = df_e[feature_cols].to_numpy(dtype=np.float32)

        if len(values) >= window:
            window_values = values[-window:]
        else:
            pad = np.zeros((window - len(values), len(feature_cols)), dtype=np.float32)
            window_values = np.vstack([pad, values])

        X.append(window_values)
        y.append(np.clip(rul_values[idx], 0, cap) / cap)

    return np.asarray(X, dtype=np.float32), np.asarray(y, dtype=np.float32), engine_ids

X_all, y_all, train_groups = create_train_sequences(train_scaled, WINDOW_SIZE, STRIDE)
X_test, y_test, test_engine_ids = create_test_windows(test_scaled, rul_truth, WINDOW_SIZE, RUL_CAP)

splitter = GroupShuffleSplit(n_splits=1, test_size=VALIDATION_SPLIT, random_state=SEED)
train_idx, val_idx = next(splitter.split(X_all, y_all, groups=train_groups))

X_train, y_train = X_all[train_idx], y_all[train_idx]
X_val, y_val = X_all[val_idx], y_all[val_idx]

print("Train:", X_train.shape, y_train.shape)
print("Val  :", X_val.shape, y_val.shape)
print("Test :", X_test.shape, y_test.shape)

def make_dataset(X, y=None, training=False):
    if y is None:
        ds = tf.data.Dataset.from_tensor_slices(X)
    else:
        ds = tf.data.Dataset.from_tensor_slices((X, y))

    if training:
        ds = ds.shuffle(min(len(X), 10000), seed=SEED, reshuffle_each_iteration=True)

    return ds.batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)

train_ds = make_dataset(X_train, y_train, training=True)
val_ds = make_dataset(X_val, y_val)
test_ds = make_dataset(X_test, y_test)

def build_model(input_shape):
    model = models.Sequential([
        layers.Input(shape=input_shape),
        layers.LSTM(128, return_sequences=True),
        layers.Dropout(0.25),
        layers.LSTM(64),
        layers.Dense(64, activation="relu"),
        layers.Dropout(0.2),
        layers.Dense(1, dtype="float32"),
    ])
    model.compile(
        optimizer=optimizers.Adam(learning_rate=LEARNING_RATE),
        loss=tf.keras.losses.Huber(),
        metrics=[tf.keras.metrics.MeanAbsoluteError(name="mae")],
    )
    return model

model = build_model((WINDOW_SIZE, len(feature_cols)))
model.summary()

cb = [
    callbacks.EarlyStopping(monitor="val_loss", patience=6, restore_best_weights=True),
    callbacks.ReduceLROnPlateau(monitor="val_loss", factor=0.5, patience=3, verbose=1),
    callbacks.ModelCheckpoint("best_rul_model.keras", monitor="val_loss", save_best_only=True),
]

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=EPOCHS,
    callbacks=cb,
    verbose=2,
)

model = tf.keras.models.load_model("best_rul_model.keras")

val_pred = model.predict(val_ds, verbose=0).flatten()
test_pred = model.predict(test_ds, verbose=0).flatten()

def evaluate_split(name, y_true_norm, y_pred_norm):
    rmse_norm = np.sqrt(mean_squared_error(y_true_norm, y_pred_norm))
    mae_norm = mean_absolute_error(y_true_norm, y_pred_norm)
    return {
        "split": name,
        "rmse_norm": rmse_norm,
        "mae_norm": mae_norm,
        "rmse_cycles": rmse_norm * RUL_CAP,
        "mae_cycles": mae_norm * RUL_CAP,
    }

metrics_df = pd.DataFrame([
    evaluate_split("validation", y_val, val_pred),
    evaluate_split("test", y_test, test_pred),
])

display(metrics_df)

plt.figure(figsize=(7, 4))
plt.plot(y_test * RUL_CAP, label="True RUL")
plt.plot(test_pred * RUL_CAP, label="Predicted RUL")
plt.title("Real Test-Set RUL Predictions")
plt.xlabel("Test engine index")
plt.ylabel("RUL (cycles)")
plt.legend()
plt.show()

@tf.function
def compute_saliency(batch_inputs):
    with tf.GradientTape() as tape:
        tape.watch(batch_inputs)
        preds = model(batch_inputs, training=False)
    grads = tape.gradient(preds, batch_inputs)
    return tf.abs(grads)

saliency_batch = tf.convert_to_tensor(X_test[: min(128, len(X_test))], dtype=tf.float32)
saliency = compute_saliency(saliency_batch).numpy()
feature_importance = saliency.mean(axis=(0, 1))

importance_df = (
    pd.DataFrame({"feature": feature_cols, "importance": feature_importance})
    .sort_values("importance", ascending=False)
    .reset_index(drop=True)
)

display(importance_df.head(10))

plt.figure(figsize=(8, 5))
sns.barplot(data=importance_df.head(10), x="importance", y="feature")
plt.title("Top Features by Gradient Saliency")
plt.show()

def inspect_test_engine(engine_id):
    idx = test_engine_ids.index(engine_id)
    window = X_test[idx:idx+1]

    pred_cycles = float(model.predict(window, verbose=0).flatten()[0] * RUL_CAP)
    true_cycles = float(y_test[idx] * RUL_CAP)

    print(f"Engine {engine_id}")
    print(f"Predicted RUL: {pred_cycles:.2f} cycles")
    print(f"True RUL     : {true_cycles:.2f} cycles")

    top_features = importance_df.head(5)["feature"].tolist()
    raw_engine = test_raw[test_raw["engine"] == engine_id].sort_values("cycle").tail(WINDOW_SIZE)

    fig, axes = plt.subplots(len(top_features), 1, figsize=(9, 2.2 * len(top_features)), sharex=True)
    if len(top_features) == 1:
        axes = [axes]

    for ax, feature in zip(axes, top_features):
        ax.plot(raw_engine["cycle"].values, raw_engine[feature].values)
        ax.set_ylabel(feature)

    axes[-1].set_xlabel("Cycle")
    plt.tight_layout()
    plt.show()

inspect_test_engine(test_engine_ids[0])

true_cycles = y_test * RUL_CAP
pred_cycles = test_pred * RUL_CAP
residuals = true_cycles - pred_cycles

fig, axes = plt.subplots(1, 2, figsize=(13, 5))

sns.scatterplot(x=true_cycles, y=pred_cycles, ax=axes[0], alpha=0.8)
min_v = min(true_cycles.min(), pred_cycles.min())
max_v = max(true_cycles.max(), pred_cycles.max())
axes[0].plot([min_v, max_v], [min_v, max_v], "r--", linewidth=2)
axes[0].set_title("True vs Predicted RUL")
axes[0].set_xlabel("True RUL (cycles)")
axes[0].set_ylabel("Predicted RUL (cycles)")

sns.histplot(residuals, bins=30, kde=True, ax=axes[1], color="teal")
axes[1].axvline(0, color="red", linestyle="--")
axes[1].set_title("Residual Distribution")
axes[1].set_xlabel("Residual (True - Predicted)")

plt.tight_layout()
plt.show()

import shap

background_size = min(64, len(X_train))
explain_size = min(20, len(X_test))

background = X_train[np.random.choice(len(X_train), background_size, replace=False)]
samples = X_test[:explain_size]

explainer = shap.GradientExplainer(model, background)
shap_values = explainer.shap_values(samples)

if isinstance(shap_values, list):
    shap_values = shap_values[0]

shap_values = np.array(shap_values)
if shap_values.ndim == 4 and shap_values.shape[-1] == 1:
    shap_values = shap_values[..., 0]

shap_importance = np.abs(shap_values).mean(axis=(0, 1))

shap_df = (
    pd.DataFrame({"feature": feature_cols, "importance": shap_importance})
    .sort_values("importance", ascending=False)
    .reset_index(drop=True)
)

display(shap_df.head(10))

plt.figure(figsize=(8, 5))
sns.barplot(data=shap_df.head(10), x="importance", y="feature", palette="mako")
plt.title("Top Features by SHAP Importance")
plt.xlabel("Mean |SHAP value|")
plt.ylabel("")
plt.show()

import os
import zipfile

model.save("best_rul_model.keras")

with zipfile.ZipFile("best_rul_model_compressed.zip", "w", zipfile.ZIP_DEFLATED) as zf:
    zf.write("best_rul_model.keras")

orig_size = os.path.getsize("best_rul_model.keras") / 1024
zip_size = os.path.getsize("best_rul_model_compressed.zip") / 1024

print(f"Original model size: {orig_size:.2f} KB")
print(f"Compressed model size: {zip_size:.2f} KB")
print(f"Reduction: {100 * (orig_size - zip_size) / orig_size:.2f}%")

import os
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers, models, mixed_precision

trained_model = model
mixed_precision.set_global_policy("float32")

def build_tflite_safe_model(input_shape):
    return models.Sequential([
        layers.Input(shape=input_shape, dtype=tf.float32),
        layers.RNN(
            layers.LSTMCell(128),
            return_sequences=True,
            unroll=True
        ),
        layers.Dropout(0.25),
        layers.RNN(
            layers.LSTMCell(64),
            unroll=True
        ),
        layers.Dense(64, activation="relu"),
        layers.Dropout(0.2),
        layers.Dense(1, dtype="float32"),
    ])

export_model = build_tflite_safe_model((WINDOW_SIZE, len(feature_cols)))

dummy = np.zeros((1, WINDOW_SIZE, len(feature_cols)), dtype=np.float32)
_ = export_model(dummy, training=False)

export_model.layers[0].cell.set_weights(trained_model.layers[0].get_weights())
export_model.layers[2].cell.set_weights(trained_model.layers[2].get_weights())
export_model.layers[3].set_weights(trained_model.layers[3].get_weights())
export_model.layers[5].set_weights(trained_model.layers[5].get_weights())

orig_pred = trained_model.predict(X_test[:32], verbose=0).flatten()
safe_pred = export_model.predict(X_test[:32].astype(np.float32), verbose=0).flatten()
print("Max abs prediction diff:", np.max(np.abs(orig_pred - safe_pred)))
print("Mean abs prediction diff:", np.mean(np.abs(orig_pred - safe_pred)))

export_model.save("best_rul_model_export_safe.keras")

converter = tf.lite.TFLiteConverter.from_keras_model(export_model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_model = converter.convert()

with open("best_rul_model_quantized.tflite", "wb") as f:
    f.write(tflite_model)

orig_size = os.path.getsize("best_rul_model_export_safe.keras") / 1024
quant_size = os.path.getsize("best_rul_model_quantized.tflite") / 1024

print(f"Safe export model size: {orig_size:.2f} KB")
print(f"Quantized TFLite size: {quant_size:.2f} KB")
print(f"Reduction: {100 * (orig_size - quant_size) / orig_size:.2f}%")
print("TFLite quantization completed successfully.")

# Run after training — paste output here
print(metrics_df.to_string(index=False))

print("Top 5 Saliency features:")
print(importance_df.head(5).to_string(index=False))
print("\nTop 5 SHAP features:")
print(shap_df.head(5).to_string(index=False))

print("Stopped at epoch:", len(history.history['loss']))
print("Best val_loss:", min(history.history['val_loss']))

import os
orig = os.path.getsize("best_rul_model.keras") / 1024
quant = os.path.getsize("best_rul_model_quantized.tflite") / 1024
print(f"Original: {orig:.2f} KB")
print(f"Quantized: {quant:.2f} KB")
print(f"Reduction: {100*(orig-quant)/orig:.2f}%")